### ISSUE TITLE
linux-dash keep loading

### ISSUE THREAD

**Issue by sjkeerthi** [afaqurk/linux-dash#319]
Hi 

I installed the linux-dash on CentOS 7.x after I loaded via apache I could see keep on loading.

Attached the screen-shot below.

![screenshot from 2015-06-24 21 32 28](https://cloud.githubusercontent.com/assets/4696166/8335017/acdf66c6-1ab8-11e5-82bd-75f12f26194a.png)
![screenshot from 2015-06-24 21 32 22](https://cloud.githubusercontent.com/assets/4696166/8335016/acdc4c0c-1ab8-11e5-910f-011c1dd0ed5d.png)

Do I really missing anything below are the rpm's I installed for linux-dash.

php-common-5.4.16-36.el7_1.x86_64
php-5.4.16-36.el7_1.x86_64
php-cli-5.4.16-36.el7_1.x86_64
php-xml-5.4.16-36.el7_1.x86_64
php-fpm-5.4.16-36.el7_1.x86_64

**Comment by sjkeerthi** [comment]
any update

**Comment by afaqurk** [comment]
Hey @sjkeerthi, I don't have enough info to help you debug this yet.

Please check the browser's console and network tab to see which calls are hanging. Also check some endpoints on backend to make sure your server is returning data. 

Also, since this involves debugging, please post it on the [Linux Dash gitter channel](https://gitter.im/afaqurk/linux-dash)

**Comment by mhellmeier** [comment]
Perhaps a similar problem:
https://github.com/afaqurk/linux-dash/issues/453
