### ISSUE TITLE
Data not pulled on cPanel account

### ISSUE THREAD

**Issue by brandonaaws** [afaqurk/linux-dash#326]
Hi,

I installed this on cPanel. Have made sure the php.ini disable function do not have exec and shell_exec in it. Still it give me no values. It shows the page with no values in it

http://screencast.com/t/mMsfTw1Wzp0I

Further investigating, the error logs shows

PHP Warning:  shell_exec() has been disabled for security reasons in /home/cpane_user/public_html/server/index.php on line 8
PHP Warning:  shell_exec() has been disabled for security reasons in /home/cpane_user/public_html/server/index.php on line 8
PHP Warning:  shell_exec() has been disabled for security reasons in /home/cpane_user/public_html/server/index.php on line 8

But I have made sure to have php.ini in each folder including public_html, servers, modules, shell_scripts and each php.ini has disable_function= " "

When I run the sh files from server, they are working but not via php.

**Comment by afaqurk** [comment]
@brandonaaws: it looks like whichever hosting provider you are using does not allow shell_exec(). This is very common with shared hosting providers. Is that the case with your setup?

In your case, your php.ini settings are simply being ignored. This can be because:
* your hosting provider does not allow overriding of php settings (common for shared hosting services)
* or less likely, your php.ini settings are not being set properly due to incorrect configuration

Unfortunately, there is nothing that can be done on the Linux Dash side to override your environment, so I can't be of much more help.

That being said, could you share which provider you are using and which type of service you are using?

**Comment by brandonaaws** [comment]
Hi,

I am the server admin. I have checked the php.ini with phpinfo and it is same php.ini being loaded which I have set. Also there is no value status for disable functions in phpinfo 

So I believe there is no issue with php.ini. I can share you links in private message if that helps.

**Comment by afaqurk** [comment]
I'm not sure the front-end link will help as we already know the error is server-side. 

If the php.ini is being loaded fine, then I assume you should not be getting shell_exec disabled error. Have you tried creating a sample test.php file in a different directory, add a similar php.ini and seeing if shell_exec works from there.

Example test.php file: 
```php 
echo shell_exec('echo hello test'); 
```

You can try accessing it via the browser and also running it via command-line 
```sh 
php test.php 
``` 

This will help us understand whether you are able to run ```shell_exec()``` in web & console when we try a very simple example.

**Comment by brandonaaws** [comment]
Hi,

Test.php is working. Even it is working on firefox as well shell.  But still no data pulled by any other source. Please allow me to share the URLs in private email. Where as we can discuss the fixes and other test here.

**Comment by afaqurk** [comment]
@brandonaaws: well, that's interesting. I saw your email.

It seems like your server is responding to each shell file request by responding with the contents of the **index.js** file in server directory.

This is happening because rather than going to the index.php file by default, your webserver is going to index.js first when a request is made to the server directory by the front-end. Obviously, since you are not running node.js, the webserver is just serving the file as text. 

I would suggest going into your server config and making sure that index.php is set as default file. This is usually the case by default in Apache if I am not mistaken. In NGINX, you have to specify it.
