### ISSUE TITLE
$interval sometime make browser and server stuck

### ISSUE THREAD

**Issue by weibangtuo** [afaqurk/linux-dash#338]
https://github.com/afaqurk/linux-dash/blob/master/js/linuxDash.js#L396
https://github.com/afaqurk/linux-dash/blob/master/js/linuxDash.js#L505

`refreshRate` is `1000 ms` as default. if `scope.getData` function execution-time longer than 1000ms, it'll make long Ajax queue, then browser and server stuck.

Usually my server response in 500ms. When busy will response out 1000ms or 2000ms. then not work well.

`$timeout` is better.

**Comment by afaqurk** [comment]
Good point, @weibangtuo . But I am not sure that using `$timeout` would solve anything. Linux Dash would still need to queue multiple `$timeout` instances due to the polling nature of requests when not using **websockets**. It would essentially be the same exact problem with more lines of code.

But you're right, I can imagine the queue getting large for slow responses from server. I am open to any suggestions to address this concern.

**Comment by triforce** [comment]
Could you not just use a $timeout and call a $timeout again when you've received a response from the server?

**Comment by afaqurk** [comment]
@triforce 
You can definitely do that but it would cause 2 problems:

* it becomes difficult to manage the cadence of the polling with `$timeout`. Instead of waiting 1000ms, the graph might be updated 100 times a second for a server with fast response time and 1 time per 3 seconds for a slow server. Since we lose control of the interval and simply queue up a `$timeout` right after the previous one finishes, it will introduce classic polling complexities about spamming servers.

* data rendered on graph will have an inconsistent time-series. When the server response time changes, the number of plot points / second for that chart will also change. This can lead to misleading graph lines when the server slows down response times and plot points stretch across the time series of the graph.

Right now, OP's original issue is limited to servers with slow response times. By making the `$timeout` change, we introduce issues for everyone, regardless of response times.

**Comment by afaqurk** [comment]
@weibangtuo : I have tried to implement a possible solution on the **interval-handling-enhancement** branch.

You can see the [changes here](https://github.com/afaqurk/linux-dash/commit/9a2638b576b48bbb65c8e00db7d2666c10d87726). An interval iteration will simply skip a server call if any previous call is still in progress. This would allow a faster server response to stay true to the interval while a slower series of server responses will cause iterations to be skipped until all calls are resolved.

Could you please try pulling down that branch and check to see if your issue is mitigated by the updates? If so, I can then proceed to clean-up the code and test it further.

Code feedback / improvements are welcome.

**Comment by weibangtuo** [comment]
:+1:
