### ISSUE TITLE
CPU/RAM Graphs not working?

### ISSUE THREAD

**Issue by zwarmapapa** [afaqurk/linux-dash#342]
I downloaded linux dash about 3 months ago and everything worked fine.

I've just updated it, and now the cpu/ram graphs don't show anymore.

http://internal.lowentry.com:5006

It runs on nginx php.

I've checked if any php function was disabled, and no php function seems to be disabled.

Any idea what it could be?

**Comment by afaqurk** [comment]
I can't tell what the issue is yet but I am investigating this issue. Seems like an issue with latest Linux Dash updates regarding websocket support.

**Comment by afaqurk** [comment]
@zwarmapapa: do you have an nginx rule which forces a reroute to index.php when it hits 404?

I ask because if you go to `http://internal.lowentry.com:5006/websocket` , it reroutes to index.php. This is what is causing your issue.

The most immediate **and temporary** resolution is to disable that forced rerouting in nginx when an error (such as 404) occurs. I will work on updating Linux Dash so it is smart enough to distinguish between a false positive (rerouted response) from a true 200 from `/websocket` URL. When that patch is released you can re-enable the forced reroute in nginx.

*A little background on the issue*:
Linux Dash uses that URL (/websocket) to distinguish whether the platform you are running supports websockets. Since we have not update anything besides Node.js to use websockets, that URL should return a 404 error. But in your case, it returns a 200, which causes the dashboard to falsely assume that websockets are supported.

**Comment by afaqurk** [comment]
@zwarmapapa please pull down latest commit for fix.

**Comment by Afforess** [comment]
I suppose one option for linux-dash would be to return a 200 and have the information on the support of websockets in the body of the response of /websocket. This would not be re-directed like a 404 would be.

However, I personally think HTTP status codes exist for a reason, and it sucks when people break the standards.

Edit: It looks like @afaqurk beat me to it and implements what I suggested.

**Comment by afaqurk** [comment]
:+1: @Afforess . Appreciate the quick response. I ended up at the same conclusion as you.

I agree about sanctity of HTTP responses. But adding an explicit HTTP response data check doesn't violate that rule but just adds to it.

**Comment by Afforess** [comment]
Yeah, I understand.

**Comment by zwarmapapa** [comment]
It works! Kudos to you!
