### ISSUE TITLE
Add support for env port

### ISSUE THREAD

**Issue by stevelacy** [afaqurk/linux-dash#388]
Hey,

Wanted to see if this would be accepted before I submitted a PR.

Would you consider adding an env option for setting the port instead of editing both go and node's config file for the port, with default to 80? Most of the systems I run and want linux-dash to run have an nginx server on port 80.

Node example:
`$ PORT=3000 npm start`
```js
server.listen(process.env.PORT || 80);
```

Similar effect for Go.

**Comment by afaqurk** [comment]
Awesome idea. Relying on the environment is a great idea and will make Linux Dash easier to configure. As long as we use a very specific, non-common prefix on all env variables. Ex: `LINUX_DASH_HTTP_PORT`.

I would suggest making the PR against the `v2.0` branch (https://github.com/afaqurk/linux-dash/tree/v2.0) instead of master.

Thanks for bringing this up.
