### ISSUE TITLE
When using node, Unable to access page from any address on lan

### ISSUE THREAD

**Issue by actuallysaf** [afaqurk/linux-dash#389]

**Comment by afaqurk** [comment]
@actuallysaf I just tried it and it worked fine for me. Do you have an error logs or reproducible steps your would like to share?

**Comment by actuallysaf** [comment]
when I type "node server/" I don't get any standout. no error but nothing showing that it was successfully started. 

I've never used node before so I could easily be doing something wrong!

**Comment by afaqurk** [comment]
You should definitely be seeing some sort of output, whether an error or successful start message.

Seems like we'll need to debug this a bit further to help you get set up with node, npm, and linux-dash. If you have time, please use the [linux dash gitter channel](gitter.im/afaqurk/linux-dash) where I can continue helping you debug this via chat rather than the slow back and forth of this issues thread.

Please run the following commands and post the result of each to help debug further:

```bash
# 1. get the node version
node -v

# 2. get the npm version
npm -v

#3. run npm install
npm i

#4. run linux dash and get the exit code
node server/ && echo $?
```

**Comment by actuallysaf** [comment]
Figured it out, needed to run "nodejs" instead of node to start the service
