### ISSUE TITLE
Linux-dash not working when python is use

### ISSUE THREAD

**Issue by eimrsha** [afaqurk/linux-dash#435]
Hi 
i am running linux-dash using the python, but i am getting only. Please help me this regard 

http://prntscr.com/grvwbf

**Comment by jongles** [comment]
I had the same issue. It was due to the wrong `Content-Type` header being sent for the css file since the file css filename is `linuxDash.min.css` and not `main.css`.

To fix, edit [line 39](https://github.com/afaqurk/linux-dash/blob/ef066014a3fb75c69819f444a0483d54f75e6b7e/app/server/index.py#L39) of `app/server/index.py` to:
>                 if self.path.startswith('/linuxDash.min.css'):

That is how I fixed the issue on my end and hopefully fixes the issue for you.

**Comment by eimrsha** [comment]
Thanks alot its work after your suggestion

**Comment by zmrow** [comment]
I updated this in https://github.com/afaqurk/linux-dash/pull/444.!

**Comment by afaqurk** [comment]
The PR by @zmrow which addressed this issue has now been merged.
