### ISSUE TITLE
Collect statistcs?

### ISSUE THREAD

**Issue by Ansem93** [afaqurk/linux-dash#438]
Hi!
linux dash is exactly what I was searching for my headless server! I need to ask some questions since I didn't find the answer in the demo:
1) Will it take statics? Example: I would like to see a cpu chart of the last  hour,day,month,year and all
2) Can it run on debian 8 or docker?
3) Can it monitor temperatures too?
4) Does it have some theme?
5) Is the developement stopped? the last update is from 5 months ago :(

**Comment by afaqurk** [comment]
> Will it take statics? Example: I would like to see a cpu chart of the last hour,day,month,year and all
This is not the purpose of Linux Dash. Its intent is to be an immediate-glance dashboard for pre-defined metrics.

> Can it run on debian 8 or docker?
Yes. When running in `docker`, it depends on which base image you use. If using a minimalist layer (ex: alpine), you might need to install some libraries. 

> Can it monitor temperatures too?
Yes. See the CPU Temperature module on Linux Dash

> Does it have some theme?
No.

> Is the developement stopped? the last update is from 5 months ago :(
No. It has slowed and is driven by community rather than the original author's contributions.
