### ISSUE TITLE
Display of  RAM not correct? 

### ISSUE THREAD

**Issue by wtrdk** [afaqurk/linux-dash#46]
Hi,

I really like this dashboard. The only thing is that the RAM usage displayed by the dashboard is very different than the RAM usage displayed by landscape-sysinfo (Ubuntu server)
The attached screenshots were made at the same time.
Ths dashboard displays usage of 73%, while landscape-sysinfo displays only 29%

EDIT:

Webmin shows roughly the same info as landscape-sysyinfo.
![screenshot 190](https://f.cloud.github.com/assets/4569244/2027597/6617d4e0-88b9-11e3-94b8-c7edebaafd35.png)

![screenshot 191](https://f.cloud.github.com/assets/4569244/2027569/ad94a9ca-88b8-11e3-869a-a9925b1ab6c3.png)
![screenshot 189](https://f.cloud.github.com/assets/4569244/2027570/ad969dd4-88b8-11e3-9d47-b845fd8c5056.png)

**Comment by shahamit** [comment]
I understand that this issue is closed but since I am facing the same issue, I hope I will get some help out.

I installed this dashboard on my "Oracle Linux Server release 6.4" vm and see a big difference in the RAM usage shown by the dashboard when compared with the "top" command.

![Output of top command](http://i.imgur.com/BUgrS6N.png)
![Linux Dashboard RAM usage](http://i.imgur.com/zEfH2HB.png)

Total RAM being 16 gb, the top command shows that only 4 GB is free while the dashboard shows 15 GB is free.
What could I by missing?

**Comment by vernes** [comment]
I hope this will help

http://serverfault.com/a/379392
